import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { randomUUID } from 'node:crypto';

async function account(page: Page) {
  await page.goto('/workspace/register');
  await page.getByLabel('Username', { exact: true }).fill('sec-' + randomUUID().slice(0,8));
  await page.locator('#password').fill('synthetic account password');
  await page.getByRole('button', { name: 'Create private workspace' }).click();
  await page.getByRole('link', { name: 'Continue to workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Start with a company.' })).toBeVisible();
}
async function openCompany(page: Page, ticker = 'AAPL') {
  await page.getByLabel('Company name, ticker or SEC CIK').fill(ticker);
  await page.locator('#company-results').getByRole('button', { name: new RegExp(ticker) }).click();
  await expect(page.locator('#company-chart svg')).toBeVisible();
}
async function openChat(page: Page) {
  if (!(await page.locator('#company-chat').isVisible())) await page.getByRole('button', {name:'Ask a question ↗'}).click();
}
test.beforeEach(async ({ context, baseURL }) => {
  await context.route('**/*', route => new URL(route.request().url()).origin === baseURL ? route.continue() : route.abort());
});

test('ticker search, financial statements, D3 inspection, evidence, export and saved questions', async ({ page }, info) => {
  const errors: string[]=[];
  page.on('pageerror', e=>errors.push(e.message));
  await account(page);
  await expect(page.getByText('Workbook library')).toHaveCount(0);
  const input = page.getByLabel('Company name, ticker or SEC CIK');
  await input.fill('APPL');
  await expect(page.locator('#company-results')).toContainText('Similar ticker');
  await input.press('ArrowDown');
  await expect(page.locator('#company-results button').first()).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('heading', { name: 'Example Devices (synthetic)', exact: true })).toBeVisible();
  await expect(page.locator('#company-chart .bw-d3-line')).toHaveCount(1);
  await expect(page.locator('#company-chart-readout')).toContainText('1.4B USD');
  if (info.project.name === 'desktop') {
    await expect(page.locator('#company-chat')).toBeVisible();
    const chatBox = (await page.locator('#company-chat').boundingBox())!;
    const mainBox = (await page.locator('.company-report-main').boundingBox())!;
    expect(mainBox.x + mainBox.width).toBeLessThanOrEqual(chatBox.x + 1);
    expect(chatBox.y + chatBox.height).toBeLessThanOrEqual(page.viewportSize()!.height + 1);
    const chartBox = (await page.locator('#company-chart').boundingBox())!;
    expect(chartBox.y + chartBox.height).toBeLessThan(page.viewportSize()!.height);
    await page.getByLabel('Question about this report').fill('Keep this draft');
    await page.getByRole('button',{name:'Close conversation'}).click();
    await openChat(page);
    await expect(page.getByLabel('Question about this report')).toHaveValue('Keep this draft');
  } else await expect(page.locator('#company-chat')).toBeHidden();
  await page.locator('#company-chart svg').focus();
  await page.keyboard.press('Home');
  await expect(page.locator('#company-chart-readout')).toContainText('2020');
  await page.keyboard.press('End');
  await expect(page.locator('#company-chart-readout')).toContainText('2025');
  await page.getByRole('button', { name: 'Quarterly', exact:true }).click();
  await expect(page.locator('#company-table thead')).toContainText('Q4 2025');
  await page.locator('#company-chart-type').selectOption('bar');
  await expect(page.locator('#company-chart .bw-d3-bar')).toHaveCount(12);
  await page.getByRole('button', { name: 'Cash flow', exact: true }).click();
  await page.locator('#company-metric').selectOption('free_cash');
  const source=page.locator('#company-table [data-source-metric=free_cash][data-source-period="Q4-2025"]');
  await source.click();
  await expect(page.getByRole('dialog')).toContainText('92,400,000 USD');
  await expect(page.getByRole('dialog')).toContainText('Operating cash flow minus');
  await expect(page.getByRole('dialog').getByRole('link')).toHaveCount(4);
  await page.getByRole('button', { name:'Close source detail' }).click();
  await expect(source).toBeFocused();
  await page.getByRole('button', { name: 'Trailing year', exact: true }).click();
  await expect(page.locator('#company-chart-readout')).toContainText('308M USD');
  await page.getByRole('button', { name: 'Business breakdowns', exact: true }).click();
  await expect(page.locator('#company-table-empty')).toContainText('No trailing-year values');
  await expect(page.locator('#company-table')).toBeHidden();
  await page.getByRole('button', { name: 'View annual values', exact: true }).click();
  await expect(page.locator('#company-table')).toContainText('Devices');
  await expect(page.locator('.company-table-group')).toContainText('Product Or Service');
  await page.getByRole('button', { name: 'Income statement', exact: true }).click();
  await page.getByRole('button', { name: 'Annual', exact: true }).click();
  await page.locator('#company-chart-type').selectOption('line');
  const download = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Export CSV' }).click();
  expect((await download).suggestedFilename()).toBe('company-0000000001-financials.csv');
  await page.screenshot({ path: info.outputPath('company-report.png'), fullPage: true });
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
  // Audit stable theme colors rather than a frame midway through a transition.
  await page.addStyleTag({ content: '*,:before,:after{transition:none!important;animation:none!important}' });
  const audit=await new AxeBuilder({page}).include('.company-workspace').withTags(['wcag2a','wcag2aa']).analyze();
  expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  await openChat(page);
  const question=page.getByLabel('Question about this report');
  await question.fill('Compare revenue in 2024 and 2025');
  await page.getByRole('button',{name:'Send question ↑'}).click();
  await expect(page.locator('.company-exchange')).toContainText('200M USD');
  await expect(page.locator('#company-chat-status')).toHaveClass(/sr-only/);
  await question.fill('Compare Q1 2025 and Q2 2025');
  await question.press('Enter');
  await expect(page.locator('.company-exchange').last()).toContainText('42M USD');
  await page.locator('.company-exchange').last().locator('.company-answer-data summary').click();
  await expect(page.locator('.company-exchange').last().locator('svg')).toBeVisible();
  await page.screenshot({ path: info.outputPath('company-conversation.png'), fullPage: false });
  await page.getByRole('button',{name:'Close conversation'}).click();
  await page.reload();
  await page.addStyleTag({ content: '*,:before,:after{transition:none!important;animation:none!important}' });
  await openChat(page);
  await expect(page.locator('.company-exchange')).toHaveCount(2);
  await page.getByRole('button',{name:'Close conversation'}).click();
  await page.getByRole('button',{name:'Toggle light and dark mode'}).click();
  const dark=await new AxeBuilder({page}).include('.company-workspace').withTags(['wcag2a','wcag2aa']).analyze();
  expect(dark.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  await page.screenshot({ path: info.outputPath('company-report-dark.png'), fullPage: true });
  await page.evaluate(() => (window as any).setTheme('ft'));
  const ft=await new AxeBuilder({page}).include('.company-workspace').withTags(['wcag2a','wcag2aa']).analyze();
  expect(ft.violations.filter(v=>['serious','critical'].includes(v.impact||''))).toEqual([]);
  await page.screenshot({ path: info.outputPath('company-report-ft.png'), fullPage: true });
  expect(errors).toEqual([]);
});

test('unavailable issuers, sector-specific rows and optional provider consent',async({page},info)=>{
  await account(page);
  await page.getByLabel('Company name, ticker or SEC CIK').fill('MISS');
  await page.locator('#company-results').getByRole('button').click();
  await expect(page.locator('#company-search-status')).toContainText('No supported annual');
  await openCompany(page,'JPM');
  await expect(page.getByRole('button',{name:'Banking',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Banking',exact:true}).click();
  await expect(page.locator('#company-table')).toContainText('Net interest income');
  await expect(page.locator('#company-metric option[value=free_cash]')).toHaveCount(0);
  const reportURL=page.url();
  await page.locator('.workspace-nav').getByRole('link',{name:'AI settings'}).click();
  const connection=page.locator('form:has(#key-deepseek)');
  await connection.locator('input[type=password]').fill('fixture-deepseek-key');
  await connection.locator('input[type=checkbox]').check();
  await connection.getByRole('button',{name:'Test and save key'}).click();
  await page.goto(reportURL);
  await openChat(page);
  await page.locator('#company-provider').selectOption('deepseek:fixture-chat');
  await expect(page.locator('#company-consent')).toBeVisible();
  expect((await page.locator('#company-chat-form').boundingBox())!.height).toBeLessThan(270);
  await page.screenshot({path:info.outputPath('company-paid-composer.png'),fullPage:false});
  await page.getByLabel('Question about this report').fill('Discuss this company');
  await page.getByRole('button',{name:'Send question ↑'}).click();
  await expect(page.locator('.company-exchange')).toHaveCount(0);
  await page.locator('#company-consent input').check();
  await page.getByRole('button',{name:'Send question ↑'}).click();
  await expect(page.locator('.company-exchange')).toContainText('AI interpretation');
  await expect(page.locator('.company-exchange')).toContainText('[S1]');
  await expect(page.locator('#company-consent input')).not.toBeChecked();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth)).toBeLessThanOrEqual(1);
});

test('Profile shows provider usage and saves controls that block paid calls', async ({ page }) => {
  await account(page);
  await page.getByRole('link', { name: /^Profile for / }).click();
  await expect(page.getByText('No API requests recorded for this period.', { exact: false })).toBeVisible();
  const footerBox=await page.getByRole('contentinfo').boundingBox();
  expect(footerBox!.x).toBe(0);
  expect(footerBox!.width).toBe(page.viewportSize()!.width);
  await page.getByRole('link', { name: 'AI settings', exact: true }).click();
  const connection = page.locator('form:has(#key-typesafe)');
  await connection.locator('input[type=password]').fill('fixture-typesafe-key');
  await connection.locator('input[type=checkbox]').check();
  await connection.getByRole('button', { name: 'Test and save key' }).click();
  await page.getByRole('link', { name: /^Profile for / }).click();
  await expect(page.getByRole('region', { name: 'Usage by provider', exact: true })).toContainText('120');
  await expect(page.getByRole('region', { name: 'Usage by provider', exact: true })).toContainText('$0.000005');
  await page.getByLabel('Maximum AI requests per 24 hours').fill('2');
  await page.getByLabel('Pause paid AI requests').check();
  await page.getByRole('button', { name: 'Save controls', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('API controls saved.');
  await page.reload();
  await expect(page.getByLabel('Pause paid AI requests')).toBeChecked();
  await expect(page.getByLabel('Maximum AI requests per 24 hours')).toHaveValue('2');
  expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  const accessibility = await new AxeBuilder({ page }).include('.profile').analyze();
  expect(accessibility.violations).toEqual([]);
  await page.getByRole('link', { name: 'AI settings', exact: true }).click();
  await connection.locator('input[type=password]').fill('fixture-typesafe-key');
  await connection.locator('input[type=checkbox]').check();
  await connection.getByRole('button', { name: 'Test and save key' }).click();
  await expect(page.getByRole('alert')).toContainText('Paid AI requests are paused');
  await page.getByRole('link', { name: /^Profile for / }).click();
  await expect(page.getByText('1 of 2 requests used in the last 24 hours.', { exact: true })).toBeVisible();
});
